default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: flight
  password: root

development:
  <<: *default
  database: fligh_development

test:
  <<: *default
  database: flight_test

production:
  <<: *default
  database: flight_production
